### PR TITLE
Ability to have grpcui not fail-fast on connection errors

### LINKED ISSUE #101: retry upstream connection
I'm using grpcui in a docker-compose app. I've got a bit of a race condition where the upstream gRPC server often doesn't start before grpcui attempts to connect to it. I'm using docker-compose `depends_on`, but this doesn't work because the container with the gRPC service reports ready when the server process has started, and not when the server is actually ready to receive connections. There's normally a few seconds in it.

Grpcui is making one attempt to connect to the upstream service, and then exiting with an error code. What i'd really like is a way to specify that it should retry the upstream connection. Is there a clean way to do this?

### PR DESCRIPTION
**Pull request by jhump**
Fixes #101.

I had originally hoped to address this with changes in the underlying `grpcurl.BlockingDial` function. And I even submitted a change to that function. However, after trying it out, I discovered that the change did not actually work -- there are other issues with `BlockingDial` that cause it to fail fast, and they are not easy to resolve, especially in a backwards-compatible way.

So I instead had to fork the dialing logic since what we want here is just completely different from `BlockingDial` -- it is very much focused on the interactive use case, and has several places that cause it to intentionally fail-fast (with as good of an error message as possible, since the error returned from `grpc.DialContext` can be bad and can obscure underlying connection error messages).

So this adds a new flag to `grpcui` so users can do `-connect-fail-fast=false`. In this mode, it does not use `grpcurl.BlockingDial` at all. Instead it uses its own dial logic that intentionally never fails fast, so it will rely on the underlying `grpc.Dial` capability to perform retries and backoff. It still does some decoration around the call to `grpc.Dial`, just to get the best error message possible (since, as mentioned above, the gRPC runtime can return bad error messages).

The first commit is not strictly necessary. That was when I was trying out the changes to `grpcurl.BlockingDial`, before realizing they were inadequate. But I left the commit here since it seems reasonable to be up-to-date with the latest releases for these dependencies.

### CODE REVIEW

File: cmd/grpcui/grpcui.go [hunk 1]
```diff
@@ -718,3 +725,91 @@ func logInfof(format string, args ...interface{}) {
...
+		c.lastErr = err
+	}
+	return conn, err
+}
+
+func (c *errTrackingDialer) err() error {
+	c.mu.Lock()
+	defer c.mu.Unlock()
+	return c.lastErr
+}
```
Comment (dragonsinth) [inline cmd/grpcui/grpcui.go:815]: Wow... it's kind of shocking that this level of invasive wrapping is needed just to get a decent error back.

At any rate, cmd/grpcui seems like a distinctly weird place for this logic to live...  at least if there were `grpcurl.DialContextWithBetterErrors`, it could be reused.  I'll approve, but I think your TODO is prescient.

**Review by dragonsinth — APPROVED** [review]
